# Generated by Django 5.1.2 on 2024-10-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_alter_location_pret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteluri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('2_stele', '**'), ('3_stele', '***'), ('4_stele', '****')], max_length=100)),
                ('telefon', models.IntegerField(verbose_name=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
