# Generated by Django 5.1.2 on 2024-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=50)),
                ('hotel', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('actualizat_la', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
