# Generated by Django 5.1.2 on 2024-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pret',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='camera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='hotel',
            field=models.CharField(max_length=50),
        ),
    ]
