# Generated by Django 5.1.2 on 2024-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_pret_alter_location_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pret',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
